name: 🐞 Bug Report (I make money using WiX) 💸
description: Found a problem while using WiX? If you're using WiX to generate revenue this is the option for you.
labels: [ "triage", "osmf" ]
type: bug

body:
  - type: markdown
    attributes:
      value: |
        ### FireGiant Support Customer?

        If you are a [FireGiant Support Customer](https://www.firegiant.com/wix-developer-direct/?utm_source=github.com&utm_medium=Display&utm_campaign=wix_issues&utm_term=support+customer&utm_content=bug_report_osmf), you can [submit bugs and questions privately](https://support.firegiant.com/requests/new).

        ### ⚠️ Everyone Else

        The WiX project maintainers do NOT use issues for questions or for help debugging why your code doesn't work; for that, [ask a question on Discussions](https://github.com/orgs/wixtoolset/discussions/new?category=questions).

        ---

  - type: input
    id: wixversion
    attributes:
      label: WiX Version
      placeholder: '6.0.0'
    validations:
      required: true

  - type: input
    id: buildversion
    attributes:
      label: .NET or MSBuild or Visual Studio Version
      description: Run "dotnet --version" or "msbuild --version" or click the Visual Studio "Help" menu, choose "About Visual Studio" and look for "Current Version".
      placeholder: '.NET 8.0.100 -or- MSBuild version 17.8.3+195e7f5a3 for .NET Framework'
    validations:
      required: true

  - type: input
    id: hwversion
    attributes:
      label: HeatWave Version
      description: If building in Visual Studio, click the Visual Studio "Help" menu, choose "About Visual Studio" and find "FireGiant HeatWave" in the Installed products list.
      placeholder: '1.0.6.1'

  - type: textarea
    id: repro
    attributes:
      label: Repro Steps
      description: Provide the steps necessary to reproduce the issue.
      value: |
        1. 
        2. 

    validations:
      required: true

  - type: input
    id: repo
    attributes:
      label: Repro Repo
      description: Create a public GitHub repo with the minimal set of code (.wixproj/.wxs/.wxl) required to reproduce the problem.
      placeholder: 'https://github.com/<userid>/<repo>'

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: 'What did you see that was unexpected? Generate [msbuild.binlog for build issues](https://learn.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild#save-a-binary-log) and bundle/verbose MSI logs for install issues'
      placeholder: Attach log files showing the problem.

    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What did you expect to see?

  - type: checkboxes
    attributes:
      label: Acknowledgements
      description: A surprising number of people skip over sections of the bug report, creating extra work for us. There are hundreds of thousands of you and only a couple of maintainers. Please take the time to fill out the form completely.
      options:
        - label: I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be [sent to Discussions](https://github.com/orgs/wixtoolset/discussions/new?category=questions)).
          required: true
        - label: I am paying the [Open Source Maintenance Fee](https://opensourcemaintenancefee.org/) by [sponsoring the `wixtoolset` project](https://github.com/sponsors/wixtoolset) because I generate revenue from my use of the WiX Toolset.
          required: true
