blank_issues_enabled: false
contact_links:
  - name: 🗨 Discussions
    about: Ask and answer questions from the volunteer community.
    url: https://github.com/orgs/wixtoolset/discussions/new?category=questions
  - name: 💵 Commercial Support
    about: Get guaranteed answers and bug fixes with a support contract from FireGiant.
    url: https://www.firegiant.com/wix-developer-direct/?utm_source=github.com&utm_medium=Display&utm_campaign=wix_issues&utm_term=commercial+support&utm_content=new_issue
