name: Page Not Found
description: Report a page not found error at https://wixtoolset.org/
title: "Page Not Found: "
labels: [ "triage" ]
body:
  - type: input
    id: page
    attributes:
      label: WiX Toolset Page URL
      placeholder: 'https://wixtoolset.org/...'
    validations:
      required: true
  - type: input
    id: ref
    attributes:
      label: Page URL that linked to WiX Toolset
      placeholder: 'https://example.com/read-about-wix.html'
  - type: textarea
    id: additional-info
    attributes:
      label: 'Additional information (optional)'
